cursor #e3e1e9
cursor_text_color #c6c5d0
foreground            #e3e1e9
background            #121318
selection_foreground  #2b3042
selection_background  #c2c5dd
url_color             #b6c4ff

# black
color0   #e3bada
color8   #e3bada

# red
color1   #ffb4ab
color9   #93000a

# green
color2   #e3bada
color10  #5b3d57

# yellow
color3   #c2c5dd
color11  #424659

# blue
color4   #b6c4ff
color12  #354479

# magenta
color5   #ffd7f5
color13  #e3bada

# cyan
color6   #dce1ff
color14  #b6c4ff

# white
color7   #e3e1e9
color15  #c6c5d0